
[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "IosevkaNerdFont"

[font.bold_italic]
family = "IosevkaNerdFont"

[font.italic]
family = "IosevkaNerdFont"

[font.normal]
family = "IosevkaNerdFont"

[general]
import = ["/home/simo/.config/alacritty/themes/monokai_pro.toml"]
